/* Supabase 登录与同步层。公开 anon key 可安全放在前端；绝不可放 service_role key。 */
// Supabase 配置由 Vercel 环境变量透过 /api/supabase-config 提供。
// 不要在这个前端文件中写入 service_role / secret key。
let cloud,cloudUser,cloudRole='teacher',localSave;
const cloudDate=()=>new Date().toLocaleDateString('sv-SE');
function cloudPanel(){document.body.insertAdjacentHTML('beforeend',`<div id="cloudLogin" style="position:fixed;inset:0;background:#17223be8;z-index:99;display:grid;place-items:center"><form id="cloudForm" style="width:min(390px,90vw);background:#fff;padding:28px;border-radius:16px;box-shadow:0 12px 44px #0005"><h2 style="margin:0 0 8px">安心托育 · 云端登录</h2><p style="color:#6e7b91;font-size:13px;margin:0 0 18px">登录后，资料会与其他老师即时同步。</p><input required name="email" type="email" placeholder="邮箱" style="width:100%;padding:11px;margin:6px 0;border:1px solid #e5eaf2;border-radius:8px"><input required name="password" type="password" placeholder="密码（至少 6 位）" minlength="6" style="width:100%;padding:11px;margin:6px 0;border:1px solid #e5eaf2;border-radius:8px"><div id="loginError" style="min-height:18px;color:#c33;font-size:12px;margin:5px 0"></div><button style="width:100%;padding:11px;border:0;border-radius:8px;background:#3478f6;color:#fff;font-weight:bold;cursor:pointer">登录</button><button type="button" id="signUp" style="width:100%;padding:10px;border:1px solid #3478f6;border-radius:8px;background:#fff;color:#3478f6;margin-top:8px;cursor:pointer">首次使用：创建老师账号</button></form></div><button id="logout" style="position:fixed;right:18px;bottom:18px;z-index:5;border:0;border-radius:99px;background:#17223b;color:#fff;padding:9px 13px;display:none;cursor:pointer">退出云端账号</button>`);document.getElementById('cloudForm').onsubmit=e=>login(e,false);document.getElementById('signUp').onclick=e=>login(e,true);document.getElementById('logout').onclick=async()=>{await cloud.auth.signOut();location.reload()}}
async function login(e,signup){if(e)e.preventDefault();let f=document.getElementById('cloudForm'),email=f.email.value,password=f.password.value,err=document.getElementById('loginError');err.textContent='';let r=signup?await cloud.auth.signUp({email,password}):await cloud.auth.signInWithPassword({email,password});if(r.error){err.textContent=r.error.message;return}if(signup&&!r.data.session){err.style.color='#078560';err.textContent='账号已创建，请按邮箱验证信后再登录。';return}await connected(r.data.user||r.data.session?.user)}
async function connected(user){cloudUser=user;let p=await cloud.from('profiles').select('role').eq('id',user.id).single();cloudRole=p.data?.role||'teacher';document.getElementById('cloudLogin').remove();document.getElementById('logout').style.display='block';await pullCloud();if(cloudRole!=='admin')document.querySelector('[data-page="admin"]').style.display='none'}
async function pullCloud(){let d=cloudDate(),[stu,att,spe,rem]=await Promise.all([cloud.from('students').select('*'),cloud.from('attendance').select('*').eq('attendance_date',d),cloud.from('special_records').select('*').eq('record_date',d),cloud.from('emergency_reminders').select('*').eq('reminder_date',d)]);if(stu.error){alert('无法读取云端资料：'+stu.error.message);return}if(stu.data.length){students=stu.data.map(x=>({id:x.id,name:x.name,grade:x.grade,meal:x.meal,diet:x.diet||'',schedule:x.schedule,teacher:x.teacher||'',group:x.group_link||'',school:[false,false],care:[false,false],special:null,notified:false}));let map=new Map((att.data||[]).map(x=>[x.student_id,x]));students.forEach(s=>{let a=map.get(s.id);if(a){s.school=[a.school_a,a.school_b];s.care=[a.care_a,a.care_b];s.notified=a.notified}});specials=(spe.data||[]).map(x=>{let s=students.find(a=>a.id===x.student_id);if(s)s.special={type:x.type,note:x.note};return {id:x.id,name:s?.name||'未知学生',type:x.type,note:x.note}});emergencies=(rem.data||[]).map(x=>({id:x.id,student:students.find(a=>a.id===x.student_id)?.name||'未知学生',time:x.reminder_time.slice(0,5),message:x.message}));localSave();renderAll()}else if(cloudRole==='admin'){await pushCloud()}}
async function pushCloud(){if(!cloudUser)return;let d=cloudDate();let attendanceRows=students.map(s=>({attendance_date:d,student_id:String(s.id),school_a:!!s.school[0],school_b:!!s.school[1],care_a:!!s.care[0],care_b:!!s.care[1],notified:!!s.notified}));let jobs=[cloud.from('attendance').upsert(attendanceRows)];if(cloudRole==='admin')jobs.push(cloud.from('students').upsert(students.map(s=>({id:String(s.id),name:s.name,grade:s.grade,meal:s.meal,diet:s.diet||'',schedule:s.schedule||'',teacher:s.teacher||'',group_link:s.group||''}))));await Promise.all(jobs);await cloud.from('special_records').delete().eq('record_date',d);await cloud.from('emergency_reminders').delete().eq('reminder_date',d);let specialRows=specials.map(x=>({record_date:d,student_id:String(students.find(s=>s.name===x.name)?.id||''),type:x.type,note:x.note})).filter(x=>x.student_id);let emergencyRows=emergencies.map(x=>({reminder_date:d,student_id:String(students.find(s=>s.name===x.student)?.id||''),reminder_time:x.time,message:x.message})).filter(x=>x.student_id);if(specialRows.length)await cloud.from('special_records').insert(specialRows);if(emergencyRows.length)await cloud.from('emergency_reminders').insert(emergencyRows)}
async function startCloud(){try{let response=await fetch('/api/supabase-config',{cache:'no-store'}),config=await response.json();if(!response.ok||!config.url||!config.anonKey)throw new Error(config.error||'缺少 Supabase 配置');cloud=window.supabase.createClient(config.url,config.anonKey);window.cloud=cloud;localSave=window.save;window.save=()=>{localSave();pushCloud().catch(console.warn)};cloudPanel();let s=await cloud.auth.getSession();if(s.data.session)connected(s.data.session.user)}catch(error){console.warn('Supabase 未连接：',error.message);alert('无法连接 Supabase。请在 Vercel 设置 SUPABASE_URL 和 SUPABASE_ANON_KEY 后重新部署。')}}

// 学生资料必须先从 Supabase 删除；否则下一次同步时会被云端旧资料还原。
window.removeStudent=async id=>{
  const student=students.find(s=>String(s.id)===String(id));
  if(!student||!confirm(`确定永久移除「${student.name}」吗？相关点名与记录也会一并清除。`))return;
  if(cloud){
    if(cloudRole!=='admin'){alert('只有管理员可以移除学生资料。');return;}
    const {error}=await cloud.from('students').delete().eq('id',String(id));
    if(error){alert('无法删除学生资料：'+error.message);return;}
  }
  students=students.filter(s=>String(s.id)!==String(id));
  specials=specials.filter(x=>x.name!==student.name);
  emergencies=emergencies.filter(x=>x.student!==student.name);
  save();
  renderAll();
  alert('学生资料已移除。');
};
window.addEventListener('load',startCloud);
