/* 新增：学生头像、每日用药提醒、吃饭点名、留校讯息、Excel 月报 */
(()=>{
  const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  const weeks=['星期一','星期二','星期三','星期四','星期五']; let stayWeek=weeks[new Date().getDay()-1]||'星期一';
  let stayRecords=JSON.parse(localStorage.getItem('careStayRecords')||'[]');
  const avatar=s=>s?.photo_url?`<img class="avatar" src="${esc(s.photo_url)}" alt="${esc(s.name)}">`:`<span class="avatar fallback">${esc(s?.name||'?').slice(0,1)}</span>`;
  function extraStyle(){if($('featureStyle'))return; document.head.insertAdjacentHTML('beforeend',`<style id="featureStyle">.avatar{width:38px;height:38px;border-radius:50%;object-fit:cover;vertical-align:middle;margin-right:10px;border:2px solid #e5eaf2}.avatar.fallback{display:inline-grid;place-items:center;background:#dff7ec;color:#078560;font-weight:800}.student .avatar{float:left;margin-top:1px}.student:has(.avatar){min-height:42px;padding-top:1px}.meal-row{display:flex;align-items:center;gap:12px;padding:13px 8px;border-top:1px solid var(--line)}.meal-row .name{flex:1;font-weight:700}.meal-row.pending{opacity:.55;font-style:italic;background:#f5f6f8}.meal-row.taken{background:#effbf6}.notes{color:#9b5b08;font-size:12px;margin-top:3px}.pill{border:0;border-radius:8px;padding:8px 12px;cursor:pointer;background:#3478f6;color:#fff;font:inherit}.pill:disabled{background:#b8c0ce;cursor:not-allowed}.photo-preview{display:none;width:52px;height:52px;object-fit:cover;border-radius:50%;margin-top:7px}</style>`)}
  function addPages(){
    const admin=$('admin'); if(!admin)return;
    if(!$('mealcheck'))admin.insertAdjacentHTML('beforebegin',`<section id="mealcheck" class="page hidden"><div class="two-col"><div class="card"><h2 class="section-title">吃饭点名</h2><p class="muted">已到托育的学生会显示绿色并可点名；应到但未到的学生为灰色斜体。</p><div id="mealCheckList"></div></div><aside class="info-panel"><h3>今日吃饭情况</h3><p>实时同步给所有老师</p><div class="ratio" id="mealRatio">0 / 0</div><div class="progress"><i id="mealProgress" style="width:0%"></i></div><div class="info-list"><div>已到托育 <b id="mealArrived">0</b> 人</div><div>已拿饭 <b id="mealTaken">0</b> 人</div><div>还没拿饭 <b id="mealPending">0</b> 人</div></div></aside></div></section><section id="stay" class="page hidden"><div class="two-col"><div class="card"><h2 class="section-title">本周留校名单</h2><div class="week-tabs" id="stayWeeks"></div><div id="stayList"></div></div><div class="card"><h2 class="section-title">添加留校讯息</h2><form id="stayForm" class="formgrid"><label>学生<select name="student" id="stayStudent"></select></label><label>星期几<select name="weekday">${weeks.map(w=>`<option>${w}</option>`).join('')}</select></label><label>需要带饭？<select name="bring_meal"><option value="true">需要带饭</option><option value="false">不需要带饭</option></select></label><label style="grid-column:1/-1">留校原因<textarea required name="reason" placeholder="例如：补习、课外活动、家长晚接"></textarea></label><button class="save" style="grid-column:1/-1">保存留校讯息</button></form></div></div></section>`);
    let form=$('studentForm'); if(form&&!form.querySelector('[name="photo"]')){form.querySelector('[name="diet"]').closest('label').insertAdjacentHTML('afterend',`<label>学生头像<input name="photo" type="file" accept="image/*" onchange="previewAvatar(this)"><img class="photo-preview" id="photoPreview"></label><label style="grid-column:1/-1">每日特别提醒 / notes<textarea name="notes" placeholder="例如：下午 1:00 需要吃感冒药"></textarea></label>`);}
    let title=admin.querySelector('.section-title'); if(title&&!title.querySelector('button'))title.insertAdjacentHTML('beforeend',' <button class="outline" style="float:right" onclick="exportMonthlyReport()">导出 Excel 月报</button>');
  }
  window.previewAvatar=input=>{let f=input.files[0],p=$('photoPreview');if(f){p.src=URL.createObjectURL(f);p.style.display='block'}};
  function options(){['stayStudent'].forEach(id=>{let el=$(id);if(el)el.innerHTML=students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')})}
  function renderMeal(){let active=students.filter(s=>!s.special),arrived=active.filter(s=>s.care?.every(Boolean)),taken=arrived.filter(s=>s.mealTaken);$('mealCheckList').innerHTML=active.map(s=>{let ok=s.care?.every(Boolean),done=!!s.mealTaken;return `<div class="meal-row ${ok?'':'pending'} ${done?'taken':''}">${avatar(s)}<div class="name">${esc(s.name)}<small style="display:block;color:#6e7b91">${esc(s.grade)} · ${esc(s.meal)}</small></div><span>${ok?(done?'✓ 已拿饭':'待拿饭'):'尚未到托育'}</span><button class="pill" ${ok?'':'disabled'} onclick="toggleMeal('${s.id}')">${done?'取消拿饭':'点名拿饭'}</button></div>`}).join('')||'<p class="muted">暂无学生。</p>';$('mealRatio').textContent=`${taken.length} / ${arrived.length}`;$('mealProgress').style.width=(arrived.length?taken.length/arrived.length*100:0)+'%';$('mealArrived').textContent=arrived.length;$('mealTaken').textContent=taken.length;$('mealPending').textContent=arrived.length-taken.length}
  window.toggleMeal=async id=>{let s=students.find(x=>String(x.id)===String(id));s.mealTaken=!s.mealTaken;save();renderMeal();if(window.cloud)await cloud.from('attendance').upsert({attendance_date:new Date().toLocaleDateString('sv-SE'),student_id:String(s.id),meal_taken:s.mealTaken})};
  function renderStay(){let el=$('stayWeeks');if(!el)return;el.innerHTML=weeks.map(w=>`<button class="${w===stayWeek?'active':''}" onclick="setStayWeek('${w}')">${w}</button>`).join('');let data=stayRecords.filter(x=>x.weekday===stayWeek);$('stayList').innerHTML=data.length?data.map((x,i)=>`<div class="emergency">${avatar(students.find(s=>String(s.id)===String(x.student_id))||{name:'?'})}<b>${esc(x.student_name)}</b><br>${x.bring_meal?'🍱 需要带饭':'无需带饭'} · ${esc(x.reason)}<br><button class="outline" onclick="removeStay(${i})">删除</button></div>`).join(''):'<p class="muted">这一天没有学生留校。</p>'}
  window.setStayWeek=w=>{stayWeek=w;renderStay()}; window.removeStay=i=>{let shown=stayRecords.filter(x=>x.weekday===stayWeek)[i];stayRecords=stayRecords.filter(x=>x!==shown);localStorage.setItem('careStayRecords',JSON.stringify(stayRecords));renderStay()};
  function bindStay(){let f=$('stayForm');if(!f||f.dataset.bound)return;f.dataset.bound=1;f.onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(f)),s=students.find(x=>String(x.id)===d.student);let record={student_id:s.id,student_name:s.name,weekday:d.weekday,bring_meal:d.bring_meal==='true',reason:d.reason};stayRecords.push(record);localStorage.setItem('careStayRecords',JSON.stringify(stayRecords));if(window.cloud)await cloud.from('stay_messages').insert(record);f.reset();renderStay()}}
  function bindStudent(){let f=$('studentForm');if(!f||f.dataset.features)return;f.dataset.features=1;const timePicker=$('sameTime'),schedule=f.elements.schedule;const setSchedule=()=>{if(!timePicker||timePicker.value==='custom')return;schedule.value=weeks.map(w=>w+' '+timePicker.value).join('；')};timePicker?.addEventListener('change',setSchedule);if(timePicker&& !schedule.value)setSchedule();f.onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(f)),file=f.elements.photo?.files?.[0],old=students.find(s=>String(s.id)===d.id),id=old?.id||Date.now(),photo=old?.photo_url||'';if(file&&window.cloud){let path=`${id}-${Date.now()}-${file.name.replace(/[^a-z0-9._-]/gi,'_')}`,up=await cloud.storage.from('student-avatars').upload(path,file,{upsert:true});if(up.error){alert('头像上传失败：'+up.error.message);return}photo=cloud.storage.from('student-avatars').getPublicUrl(path).data.publicUrl}let data={...d,id,photo_url:photo};delete data.photo;delete data.sameTime;if(old)Object.assign(old,data);else students.push({...data,school:[false,false],care:[false,false],special:null,notified:false,mealTaken:false});if(window.cloud)await cloud.from('students').upsert({id:String(id),name:data.name,grade:data.grade,meal:data.meal,diet:data.diet||'',schedule:data.schedule,teacher:data.teacher||'',group_link:data.group||'',photo_url:photo,notes:data.notes||''});save();resetStudentForm();renderAll();alert('学生资料已保存')};}
  function reminders(){let list=students.filter(s=>s.notes?.trim());if(!list.length)return;let old=$('dailyNotes');if(old)old.remove();let target=document.querySelector('#summary .card[style]')||$('summary');target.insertAdjacentHTML('afterend',`<div id="dailyNotes" class="card" style="margin-top:18px;border-left:4px solid #f3943f"><h2 class="section-title">💊 每日特别提醒</h2>${list.map(s=>`<div class="emergency">${avatar(s)}<b>${esc(s.name)}</b><br>${esc(s.notes)}</div>`).join('')}</div>`)}
  function decorateAttendance(){document.querySelectorAll('#schoolList .student,#careList .student').forEach(el=>{let s=students.find(x=>el.textContent.trim().startsWith(x.name));if(s&&!el.querySelector('.avatar'))el.insertAdjacentHTML('afterbegin',avatar(s));if(s?.notes&&!el.querySelector('.notes'))el.insertAdjacentHTML('beforeend',`<small class="notes">💊 ${esc(s.notes)}</small>`)});}
  window.exportMonthlyReport=async()=>{let now=new Date(),month=now.toISOString().slice(0,7),rows=[];if(window.cloud){let q=await cloud.from('attendance').select('attendance_date,student_id,care_a,care_b').gte('attendance_date',month+'-01').lt('attendance_date',new Date(now.getFullYear(),now.getMonth()+1,1).toISOString().slice(0,10));rows=q.data||[]}let report=students.map(s=>{let a=rows.filter(r=>String(r.student_id)===String(s.id)),present=a.filter(r=>r.care_a&&r.care_b).length;return {'学生':s.name,'年级':s.grade,'本月应到天数':a.length,'已到托育天数':present,'出席率':a.length?Math.round(present/a.length*100)+'%':'—'}});if(!window.XLSX){alert('Excel 工具载入失败，请检查网络连接。');return}let ws=XLSX.utils.json_to_sheet(report),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'月出席率');XLSX.writeFile(wb,`安心托育_${month}_考勤月报.xlsx`)};
  const originalRender=window.renderAll; window.renderAll=()=>{originalRender?.();extraStyle();addPages();decorateAttendance();options();renderMeal();renderStay();reminders();bindStay();bindStudent()};
  const originalToggle=window.toggle; if(originalToggle)window.toggle=(...args)=>{originalToggle(...args);decorateAttendance();renderMeal();reminders()};
  const originalPull=window.pullCloud; if(originalPull)window.pullCloud=async()=>{await originalPull();if(window.cloud){let r=await cloud.from('students').select('id,photo_url,notes'),a=await cloud.from('attendance').select('student_id,meal_taken').eq('attendance_date',new Date().toLocaleDateString('sv-SE')),t=await cloud.from('stay_messages').select('*');(r.data||[]).forEach(x=>{let s=students.find(y=>String(y.id)===String(x.id));if(s)Object.assign(s,{photo_url:x.photo_url||'',notes:x.notes||''})});(a.data||[]).forEach(x=>{let s=students.find(y=>String(y.id)===String(x.student_id));if(s)s.mealTaken=!!x.meal_taken});if(t.data){stayRecords=t.data.map(x=>({...x,student_name:students.find(s=>String(s.id)===String(x.student_id))?.name||'未知学生'}));localStorage.setItem('careStayRecords',JSON.stringify(stayRecords))}}renderAll()};
  window.addEventListener('load',()=>setTimeout(()=>{extraStyle();addPages();decorateAttendance();options();renderMeal();renderStay();reminders();bindStay();bindStudent()},100));
})();
