/* 学生日常记录与管理员点名清除 */
(()=>{
  const $=id=>document.getElementById(id),weeks=['星期一','星期二','星期三','星期四','星期五'],grades=['一年级','二年级','三年级','四年级','五年级','六年级'];
  let stage='低年段',grade='全部';const storeKey='fuchengDailyRecords';
  const records=()=>{try{return JSON.parse(localStorage.getItem(storeKey)||'[]')}catch{return []}},saveRecords=x=>localStorage.setItem(storeKey,JSON.stringify(x));
  const find=n=>students.find(s=>s.name===String(n||'').trim()),esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  function addPage(){if($('dailyrecord'))return;let anchor=$('admin');anchor.insertAdjacentHTML('beforebegin',`<section id="dailyrecord" class="page hidden"><div class="two-col"><div class="card"><h2 class="section-title">今日学生日常记录</h2><div class="week-tabs" id="recordStage"></div><div class="time-tabs" id="recordGrade"></div><div id="dailyRecordList"></div></div><div class="card"><h2 class="section-title">新增记录</h2><form id="dailyRecordForm" class="formgrid"><label style="grid-column:1/-1">学生姓名<input required name="student" list="recordStudents" placeholder="输入学生姓名搜索"></label><datalist id="recordStudents"></datalist><label style="grid-column:1/-1">今日情况<textarea required name="note" placeholder="例如：功课还没完成；今天情绪较好；已完成阅读"></textarea></label><button class="save" style="grid-column:1/-1">保存日常记录</button></form></div></div></section>`);let nav=document.querySelector('.nav');nav.insertAdjacentHTML('beforeend','<button data-page="dailyrecord"><b class="num">07</b> 学生日常记录</button>');let b=nav.querySelector('[data-page="dailyrecord"]');b.onclick=e=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));e.currentTarget.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('dailyrecord').classList.remove('hidden');$('pageTitle').textContent='学生日常记录';render()};$('dailyRecordForm').onsubmit=async e=>{e.preventDefault();let f=e.currentTarget,s=find(f.student.value);if(!s)return alert('请从提示名单中输入正确的学生姓名。');let item={id:Date.now().toString(),student_id:String(s.id),student_name:s.name,record_date:new Date().toLocaleDateString('sv-SE'),note:f.note.value.trim()};let list=records();list.push(item);saveRecords(list);if(window.cloud)await cloud.from('daily_student_records').insert(item).catch(()=>{});f.reset();render()}}
  function tabs(id,items,current,set){let el=$(id);if(el)el.innerHTML=items.map(v=>`<button class="${v===current?'active':''}" onclick="${set}('${v}')">${v}</button>`).join('')}
  window.setRecordStage=v=>{stage=v;grade='全部';render()};window.setRecordGrade=v=>{grade=v;render()};
  function render(){if(!$('dailyRecordList'))return;let g=stage==='低年段'?grades.slice(0,3):grades.slice(3);tabs('recordStage',['低年段','高年段'],stage,'setRecordStage');tabs('recordGrade',['全部',...g],grade,'setRecordGrade');$('recordStudents').innerHTML=students.map(s=>`<option value="${esc(s.name)}"></option>`).join('');let allowed=students.filter(s=>(grade==='全部'?g.includes(s.grade):s.grade===grade));let list=records().filter(r=>r.record_date===new Date().toLocaleDateString('sv-SE')&&allowed.some(s=>String(s.id)===r.student_id));$('dailyRecordList').innerHTML=list.length?list.map((r,i)=>{let s=find(r.student_name);let avatar=s?.photo_url?`<img class="avatar" src="${esc(s.photo_url)}">`:`<span class="avatar fallback">${esc(r.student_name).slice(0,1)}</span>`;return `<div class="emergency">${avatar}<b>${esc(r.student_name)}</b><br>${esc(r.note)}<br><button class="outline" onclick="deleteDailyRecord(${i})">删除</button></div>`}).join(''):'<p class="muted">这个年段今天还没有日常记录。</p>'}
  window.deleteDailyRecord=i=>{let g=stage==='低年段'?grades.slice(0,3):grades.slice(3),allowed=students.filter(s=>(grade==='全部'?g.includes(s.grade):s.grade===grade)),shown=records().filter(r=>r.record_date===new Date().toLocaleDateString('sv-SE')&&allowed.some(s=>String(s.id)===r.student_id))[i],list=records().filter(x=>x!==shown);saveRecords(list);if(window.cloud&&shown?.id)cloud.from('daily_student_records').delete().eq('id',shown.id).catch(()=>{});render()};
  window.clearTodayAttendance=async()=>{if(window.cloud&&window.cloudRole!=='admin')return alert('只有管理员可以清除点名状态。');if(!confirm('确定清除今天所有学校、托育及吃饭点名状态吗？此操作无法自动恢复。'))return;students.forEach(s=>{s.school=[false,false];s.care=[false,false];s.mealTaken=false;s.notified=false});save();if(window.cloud)await cloud.from('attendance').delete().eq('attendance_date',new Date().toLocaleDateString('sv-SE'));renderAll();alert('今天的点名状态已清除。')};
  function adminButton(){let t=$('admin')?.querySelector('.section-title');if(t&&!$('clearAttendanceBtn'))t.insertAdjacentHTML('beforeend',' <button id="clearAttendanceBtn" class="outline" style="float:right;margin-left:7px;color:#c33;border-color:#e25c69" onclick="clearTodayAttendance()">清除今日点名</button>')}
  function order(){let nav=document.querySelector('.nav'),seq=['summary','school','care','mealcheck','stay','tuition','dailyrecord','admin','special','emergency'];seq.forEach((p,i)=>{let b=nav.querySelector(`[data-page="${p}"]`);if(b){b.querySelector('.num').textContent=String(i+1).padStart(2,'0');nav.appendChild(b)}})}
  window.addEventListener('load',()=>setTimeout(()=>{addPage();adminButton();order();render()},1200));
})();

/* 确认后才可发送通知；日常记录直接列出全部学生 */
(()=>{
  const $=id=>document.getElementById(id),grades=['一年级','二年级','三年级','四年级','五年级','六年级'],today=new Date().toLocaleDateString('sv-SE');let stage='低年段',grade='全部';
  const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  const recs=()=>{try{return JSON.parse(localStorage.getItem('fuchengDailyRecords')||'[]')}catch{return []}},put=x=>localStorage.setItem('fuchengDailyRecords',JSON.stringify(x));
  const stageGrades=()=>stage==='低年段'?grades.slice(0,3):grades.slice(3);
  function tabs(id,items,current,fn){let el=$(id);if(el)el.innerHTML=items.map(v=>`<button class="${v===current?'active':''}" onclick="${fn}('${v}')">${v}</button>`).join('')}
  function dailyRender(){if(!$('dailyrecord'))return;let g=stageGrades(),show=students.filter(s=>(grade==='全部'?g.includes(s.grade):s.grade===grade)),data=recs().filter(x=>x.record_date===today);tabs('recordStage',['低年段','高年段'],stage,'dailySetStage');tabs('recordGrade',['全部',...g],grade,'dailySetGrade');$('dailyRecordList').innerHTML=show.map(s=>{let av=s.photo_url?`<img class="avatar" src="${esc(s.photo_url)}">`:`<span class="avatar fallback">${esc(s.name).slice(0,1)}</span>`,own=data.filter(x=>String(x.student_id)===String(s.id));return `<div class="emergency" style="border-left-color:#3478f6">${av}<b>${esc(s.name)}</b> · ${esc(s.grade)}<textarea id="daily-${s.id}" placeholder="输入今天的情况，例如：功课还没完成"></textarea><button class="save" style="margin-top:7px" onclick="addDailyRecord('${s.id}')">添加情况</button>${own.map(r=>`<div style="margin-top:8px;padding-top:8px;border-top:1px solid #dbe5f6">${esc(r.note)} <button class="outline" style="float:right" onclick="deleteDailyRecordById('${r.id}')">删除</button></div>`).join('')}</div>`}).join('')||'<p class="muted">这个年段没有学生。</p>'}
  window.dailySetStage=v=>{stage=v;grade='全部';dailyRender()};window.dailySetGrade=v=>{grade=v;dailyRender()};
  window.addDailyRecord=async id=>{let s=students.find(x=>String(x.id)===String(id)),input=$('daily-'+id),note=input?.value.trim();if(!s||!note)return alert('请先输入学生今天的情况。');let item={id:Date.now().toString(),student_id:String(s.id),student_name:s.name,record_date:today,note},data=recs();data.push(item);put(data);if(window.cloud)await cloud.from('daily_student_records').insert(item).catch(()=>{});dailyRender()};
  window.deleteDailyRecordById=async id=>{let data=recs(),item=data.find(x=>String(x.id)===String(id));put(data.filter(x=>String(x.id)!==String(id)));if(window.cloud&&item)await cloud.from('daily_student_records').delete().eq('id',id).catch(()=>{});dailyRender()};
  function secureRow(s,kind){let schoolOK=s.school?.every(Boolean),careOK=s.care?.every(Boolean),blocked=kind==='care'&&!schoolOK,done=kind==='school'?schoolOK:careOK,disabled=s.special||blocked;let state=s.special?`<span class="tag red">${esc(s.special.type)}</span>`:done?'<span class="tag green">已确认</span>':blocked?'<span class="tag">等待学校确认</span>':'<span class="tag">待确认</span>';let canSend=kind==='school'?schoolOK:careOK;let note=kind==='school'?(s.diet?'特殊餐：'+esc(s.diet):'—'):'';let send=`<button class="${canSend?'greenbtn':'outline'}" style="margin:0;padding:7px 9px;${canSend?'':'opacity:.45;cursor:not-allowed'}" ${canSend?'':'disabled'} onclick="shareStudentWhatsapp('${s.id}')">${s.notified?'已发送':'发信息通知'}</button>`;return `<div class="attendance-row ${done?'confirmed':''} ${s.special?'unavailable':''}"><div class="student">${esc(s.name)}<small>${esc(s.grade)} · ${esc(s.meal)}</small></div><label class="check"><input type="checkbox" ${s[kind][0]?'checked':''} ${disabled?'disabled':''} onchange="toggle('${s.id}','${kind}',0,this.checked)">确认</label><label class="check"><input type="checkbox" ${s[kind][1]?'checked':''} ${disabled?'disabled':''} onchange="toggle('${s.id}','${kind}',1,this.checked)">确认</label><div>${state}</div><div>${kind==='school'?`${note}<br>${send}`:send}</div></div>`}
  window.addEventListener('load',()=>setTimeout(()=>{window.row=secureRow;let old=document.querySelector('[data-page="dailyrecord"]');if(old)old.onclick=e=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));e.currentTarget.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('dailyrecord').classList.remove('hidden');$('pageTitle').textContent='学生日常记录';dailyRender()};let form=$('dailyRecordForm');if(form){form.closest('.card').querySelector('h2').textContent='全部学生 · 今日情况';form.remove()}dailyRender();renderAttendance()},1600));
})();

/* 后台左侧底部：只清除误点的「已发送」通知状态；隔天重置吃饭点名 */
(()=>{
  const today=new Date().toLocaleDateString('sv-SE'),key='fuchengMealAttendanceDate',last=localStorage.getItem(key);
  if(last&&last!==today){students.forEach(s=>s.mealTaken=false);save()}localStorage.setItem(key,today);
  window.clearSentStatus=async()=>{if(window.cloud&&window.cloudRole!=='admin')return alert('只有管理员可以清除发送状态。');if(!confirm('确定清除今天所有“已发送”通知状态吗？出勤点名不会被清除。'))return;students.forEach(s=>s.notified=false);save();if(window.cloud){let rows=students.map(s=>({attendance_date:today,student_id:String(s.id),notified:false}));await cloud.from('attendance').upsert(rows)}renderAttendance();alert('已清除发送状态。')};
  window.addEventListener('load',()=>setTimeout(()=>{let panel=document.querySelector('#admin .two-col > .card');if(panel&&!document.getElementById('clearSentStatusBtn'))panel.insertAdjacentHTML('beforeend','<div style="margin-top:16px;text-align:right"><button id="clearSentStatusBtn" class="outline" style="color:#c33;border-color:#e25c69" onclick="clearSentStatus()">清除今日“已发送”状态</button></div>')},1300));
})();
