/* 搜索学生、分年段吃饭点名与学生补习时间 */
(()=>{
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
 const weeks=['星期一','星期二','星期三','星期四','星期五'],grades=['一年级','二年级','三年级','四年级','五年级','六年级'];let mwStage='低年段',mwGrade='全部',tuWeek='星期一',tuTime='',tuStage='低年段',tuGrade='全部';
 const find=name=>students.find(s=>s.name===String(name).trim());
 const low=g=>grades.slice(0,3).includes(g);
 function searchInput(id,placeholder){return `<input id="${id}" list="studentNames" autocomplete="off" placeholder="${placeholder||'输入学生姓名搜索'}">`}
 function datalist(){let d=$('studentNames');if(!d){document.body.insertAdjacentHTML('beforeend','<datalist id="studentNames"></datalist>');d=$('studentNames')}d.innerHTML=students.map(s=>`<option value="${esc(s.name)}"></option>`).join('')}
 function tabs(id,items,current,fn){let el=$(id);if(el)el.innerHTML=items.map(x=>`<button class="${x===current?'active':''}" onclick="${fn}('${x}')">${x}</button>`).join('')}
 function add(){let admin=$('admin');if(!admin||$('tuition'))return;admin.insertAdjacentHTML('beforebegin',`<section id="tuition" class="page hidden"><div class="card"><h2 class="section-title">学生补习时间</h2><div class="week-tabs" id="tuWeek"></div><div class="time-tabs" id="tuTime"></div><div class="week-tabs" id="tuStage"></div><div class="time-tabs" id="tuGrade"></div><div id="tuitionList"></div></div></section>`);let nav=document.querySelector('.nav');nav.insertAdjacentHTML('beforeend','<button data-page="tuition"><b class="num">09</b> 学生补习时间</button>');document.querySelector('[data-page="tuition"]').onclick=e=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));e.currentTarget.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('tuition').classList.remove('hidden');$('pageTitle').textContent='学生补习时间';renderTuition()};let form=$('studentForm');if(form&&!form.querySelector('[name="tuition"]'))form.querySelector('[name="notes"]').closest('label').insertAdjacentHTML('afterend',`<label style="grid-column:1/-1">学生补习信息<textarea name="tuition" placeholder="格式：星期一 15:00｜张老师｜数学｜学校 A 栋；星期三 16:30｜李老师｜英文｜补习中心"></textarea></label>`)}
 function meal(){let root=$('mealcheck');if(!root)return;let card=root.querySelector('.card');if(!$('#mealStage'))card.querySelector('.muted').insertAdjacentHTML('afterend','<div class="week-tabs" id="mealStage"></div><div class="time-tabs" id="mealGrade"></div>');tabs('mealStage',['低年段','高年段'],mwStage,'setMealStage');let gs=mwStage==='低年段'?grades.slice(0,3):grades.slice(3);tabs('mealGrade',['全部',...gs],mwGrade,'setMealGrade');let old=window.renderMeal;window.renderMeal=()=>{let active=students.filter(s=>!s.special&&(mwGrade==='全部'?(mwStage==='低年段'?low(s.grade):!low(s.grade)):s.grade===mwGrade)),arrived=active.filter(s=>s.care?.every(Boolean)),taken=arrived.filter(s=>s.mealTaken);$('mealCheckList').innerHTML=active.map(s=>{let ok=s.care?.every(Boolean),done=!!s.mealTaken,avatar=s.photo_url?`<img class="avatar" src="${esc(s.photo_url)}">`:`<span class="avatar fallback">${esc(s.name).slice(0,1)}</span>`;return `<div class="meal-row ${ok?'':'pending'} ${done?'taken':''}">${avatar}<div class="name">${esc(s.name)}<small style="display:block;color:#6e7b91">${esc(s.grade)} · ${esc(s.meal)}</small></div><span>${ok?(done?'✓ 已拿饭':'待拿饭'):'尚未到托育'}</span><button class="pill" ${ok?'':'disabled'} onclick="toggleMeal('${s.id}')">${done?'取消拿饭':'点名拿饭'}</button></div>`}).join('')||'<p class="muted">这个年段暂时没有学生。</p>';$('mealRatio').textContent=`${taken.length} / ${arrived.length}`;$('mealProgress').style.width=(arrived.length?taken.length/arrived.length*100:0)+'%';$('mealArrived').textContent=arrived.length;$('mealTaken').textContent=taken.length;$('mealPending').textContent=arrived.length-taken.length};window.renderMeal();}
 window.setMealStage=v=>{mwStage=v;mwGrade='全部';meal()};window.setMealGrade=v=>{mwGrade=v;meal()};
 function parse(s){return String(s||'').split(/[；;\n]+/).map(x=>{let p=x.trim().split(/[｜|]/).map(a=>a.trim()),m=p[0]?.match(/(星期[一二三四五])\s*(\d{1,2}:\d{2})/);return m?{week:m[1],time:m[2],teacher:p[1]||'',subject:p[2]||'',place:p[3]||'',raw:x}:null}).filter(Boolean)}
 function renderTuition(){tabs('tuWeek',weeks,tuWeek,'setTuWeek');let all=[...new Set(students.flatMap(s=>parse(s.tuition).filter(x=>x.week===tuWeek).map(x=>x.time)))].sort();if(!all.includes(tuTime))tuTime=all[0]||'';tabs('tuTime',all.length?all:['暂无补习时间'],tuTime||'暂无补习时间','setTuTime');tabs('tuStage',['低年段','高年段'],tuStage,'setTuStage');let gs=tuStage==='低年段'?grades.slice(0,3):grades.slice(3);tabs('tuGrade',['全部',...gs],tuGrade,'setTuGrade');let list=students.filter(s=>(tuGrade==='全部'?(tuStage==='低年段'?low(s.grade):!low(s.grade)):s.grade===tuGrade)).flatMap(s=>parse(s.tuition).filter(x=>x.week===tuWeek&&(!tuTime||x.time===tuTime)).map(x=>({s,x})));$('tuitionList').innerHTML=list.length?list.map(({s,x})=>`<div class="emergency"><b>${esc(s.name)}</b> · ${esc(s.grade)}<br><b>${esc(x.week)} ${esc(x.time)}</b>　${esc(x.subject||'补习')} · ${esc(x.teacher||'未填写老师')}<br><span class="muted">地点：${esc(x.place||'未填写')}</span></div>`).join(''):'<p class="muted">没有符合条件的补习资料。</p>'}
 window.setTuWeek=v=>{tuWeek=v;tuTime='';renderTuition()};window.setTuTime=v=>{tuTime=v==='暂无补习时间'?'':v;renderTuition()};window.setTuStage=v=>{tuStage=v;tuGrade='全部';renderTuition()};window.setTuGrade=v=>{tuGrade=v;renderTuition()};
 function searchForms(){datalist();let special=$('specialStudent'),emergency=$('emergencyStudent'),stay=$('stayStudent');if(special&&special.tagName==='SELECT')special.outerHTML=searchInput('specialStudent');if(emergency&&emergency.tagName==='SELECT')emergency.outerHTML=searchInput('emergencyStudent');if(stay&&stay.tagName==='SELECT')stay.outerHTML=searchInput('stayStudent');window.addSpecial=()=>{let s=find($('specialStudent').value);if(!s)return alert('请从提示名单中输入正确的学生姓名。');let type=$('specialType').value,note=$('specialNote').value||type;s.special={type,note};specials.push({name:s.name,type,note});save();renderAll();$('specialNote').value=''};let ef=$('emergencyForm');if(ef)ef.onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(ef)),s=find(d.student);if(!s)return alert('请先输入正确的学生姓名。');emergencies.push({student:s.name,time:d.time,message:d.message});save();renderEmergency();ef.reset()};let sf=$('stayForm');if(sf)sf.onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(sf)),s=find(d.student);if(!s)return alert('请先输入正确的学生姓名。');let r={student_id:s.id,student_name:s.name,weekday:d.weekday,bring_meal:d.bring_meal==='true',reason:d.reason};stayRecords.push(r);localStorage.setItem('careStayRecords',JSON.stringify(stayRecords));if(window.cloud)await cloud.from('stay_messages').insert(r);sf.reset();window.renderAll()}}
 function tuitionForm(){let f=$('studentForm');if(!f||f.dataset.tuition)return;f.dataset.tuition=1;let old=f.onsubmit;f.onsubmit=async e=>{let name=f.elements.name.value,tuition=f.elements.tuition?.value||'';await old(e);let s=students.find(x=>x.name===name);if(s){s.tuition=tuition;if(window.cloud)await cloud.from('students').update({tuition_info:tuition}).eq('id',String(s.id));save()}}}
 const priorPull=window.pullCloud;if(priorPull)window.pullCloud=async()=>{await priorPull();if(window.cloud){let r=await cloud.from('students').select('id,tuition_info');(r.data||[]).forEach(x=>{let s=students.find(y=>String(y.id)===String(x.id));if(s)s.tuition=x.tuition_info||''})}renderTuition()};
 const priorEdit=window.editStudent;if(priorEdit)window.editStudent=id=>{priorEdit(id);let s=students.find(x=>String(x.id)===String(id));if($('studentForm').elements.tuition)$('studentForm').elements.tuition.value=s?.tuition||''};
 function brand(){document.title='辅成托育中心 · 点名系统';let b=document.querySelector('.brand');if(b)b.innerHTML='<img src="/logo" alt="辅成托育中心 LOGO"><span>辅成托育中心</span>';document.head.insertAdjacentHTML('beforeend','<style id="brandStyle">.brand{display:flex;align-items:center;gap:10px;padding-bottom:24px}.brand img{width:58px;height:58px;object-fit:contain;background:#fff;border-radius:50%;padding:2px}.brand span{margin:0;color:#fff;font-size:17px;font-weight:800;line-height:1.2}@media(max-width:900px){.brand{padding:0 0 20px;justify-content:center}.brand:before{display:none}.brand img{width:42px;height:42px}.brand span{display:none}}</style>');let replace=()=>document.querySelectorAll('h2').forEach(x=>{if(x.textContent.includes('安心托育'))x.textContent=x.textContent.replaceAll('安心托育','辅成托育中心')});replace();new MutationObserver(replace).observe(document.body,{childList:true,subtree:true})}
 window.addEventListener('load',()=>setTimeout(()=>{brand();add();meal();searchForms();tuitionForm();renderTuition()},250));
})();

/* 补习资料展示修复：兼容一般中文输入，并即时刷新 */
(()=>{
  const weeks=['星期一','星期二','星期三','星期四','星期五'],grades=['一年级','二年级','三年级','四年级','五年级','六年级'];let week='星期一',time='',stage='低年段',grade='全部';
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  const stageMatch=s=>stage==='低年段'?grades.slice(0,3).includes(s.grade):grades.slice(3).includes(s.grade);
  function parse(text){return String(text||'').split(/[；;\n]+/).map(raw=>{let m=raw.match(/(星期[一二三四五])[^0-9]*?(\d{1,2}(?::\d{2})?)/);if(!m)return null;let parts=raw.split(/[｜|，,]/).map(x=>x.trim()).filter(Boolean);let t=m[2].includes(':')?m[2]:m[2]+':00';return {week:m[1],time:t,teacher:parts[1]||'',subject:parts[2]||'',place:parts[3]||'',raw}}).filter(Boolean)}
  function buttonRow(id,values,current,click){let el=$(id);if(!el)return;el.replaceChildren(...values.map(v=>{let b=document.createElement('button');b.textContent=v;b.className=v===current?'active':'';b.onclick=()=>{click(v);draw()};return b}))}
  function draw(){if(!$('tuitionList'))return;let all=students.filter(s=>stageMatch(s)&&(grade==='全部'||s.grade===grade)).flatMap(s=>parse(s.tuition).filter(x=>x.week===week).map(x=>({...x,s})));let times=[...new Set(all.map(x=>x.time))].sort();if(!times.includes(time))time=times[0]||'';buttonRow('tuWeek',weeks,week,v=>{week=v;time=''});buttonRow('tuTime',times.length?times:['暂无补习时间'],time||'暂无补习时间',v=>{time=v==='暂无补习时间'?'':v});buttonRow('tuStage',['低年段','高年段'],stage,v=>{stage=v;grade='全部';time=''});let gs=stage==='低年段'?grades.slice(0,3):grades.slice(3);buttonRow('tuGrade',['全部',...gs],grade,v=>{grade=v;time=''});let shown=all.filter(x=>!time||x.time===time);$('tuitionList').innerHTML=shown.length?shown.map(({s,x})=>`<div class="emergency"><b>${esc(s.name)}</b> · ${esc(s.grade)}<br><b>${esc(x.week)} ${esc(x.time)}</b>${x.teacher?' · '+esc(x.teacher):''}${x.subject?' · '+esc(x.subject):''}${x.place?'<br><span class="muted">地点：'+esc(x.place)+'</span>':''}<br><span class="muted">${esc(x.raw)}</span></div>`).join(''):'<p class="muted">这个星期、时间和年级筛选没有补习资料。</p>'}
  window.addEventListener('load',()=>setTimeout(()=>{let nav=document.querySelector('[data-page="tuition"]');if(nav)nav.onclick=e=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));e.currentTarget.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('tuition').classList.remove('hidden');$('pageTitle').textContent='学生补习时间';draw()};let f=$('studentForm');if(f)f.addEventListener('submit',()=>setTimeout(draw,30));draw()},800));
})();

/* 最终可靠性层：保留补习资料，并让通知按钮始终有明确反馈 */
(()=>{
  const tuitionKey='careTuitionByStudentId';
  const readTuition=()=>{try{return JSON.parse(localStorage.getItem(tuitionKey)||'{}')}catch{return {}}};
  const writeTuition=data=>localStorage.setItem(tuitionKey,JSON.stringify(data));
  function restoreTuition(){let saved=readTuition();students.forEach(s=>{if(!s.tuition&&saved[String(s.id)])s.tuition=saved[String(s.id)]})}
  function rememberTuition(id,value){let saved=readTuition();saved[String(id)]=value||'';writeTuition(saved)}
  function copyText(value){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(value).catch(()=>false);let t=document.createElement('textarea');t.value=value;document.body.append(t);t.select();document.execCommand('copy');t.remove();return Promise.resolve(true)}
  window.shareStudentWhatsapp=id=>{let s=students.find(x=>String(x.id)===String(id));if(!s)return alert('找不到这位学生，请刷新页面后再试。');let message=`【辅成托育中心通知】\n${s.name} 已安全到达托育中心。`;s.notified=true;save();copyText(message);let url=(s.group||'').trim();if(!/^https?:\/\//.test(url)||url.includes('/example'))url='https://web.whatsapp.com/send?text='+encodeURIComponent(message);let popup=window.open(url,'_blank');if(!popup)location.href=url;alert('通知文案已复制，并已打开 WhatsApp。请在群组中粘贴后发送。');renderAttendance()};
  const priorPullReliable=window.pullCloud;if(priorPullReliable)window.pullCloud=async()=>{let before=readTuition();try{let cached=JSON.parse(localStorage.getItem('careStudents')||'[]');cached.forEach(s=>{if(s.tuition&&!before[String(s.id)])before[String(s.id)]=s.tuition})}catch{}await priorPullReliable();students.forEach(s=>{if(before[String(s.id)]&&!s.tuition)s.tuition=before[String(s.id)]});writeTuition(before)};
  window.addEventListener('load',()=>setTimeout(()=>{restoreTuition();let f=document.getElementById('studentForm');if(!f||f.dataset.tuitionReliable)return;f.dataset.tuitionReliable='1';f.addEventListener('submit',()=>{let id=f.elements.id?.value,name=f.elements.name?.value,value=f.elements.tuition?.value||'';setTimeout(async()=>{let s=students.find(x=>String(x.id)===String(id))||students.find(x=>x.name===name);if(!s)return;s.tuition=value;rememberTuition(s.id,value);save();if(window.cloud)await cloud.from('students').update({tuition_info:value}).eq('id',String(s.id))},0)},true)},650));
})();

/* 稳定性修复：避免重复筛选项、恢复修改资料与学校/托育联动 */
(()=>{
  const $=id=>document.getElementById(id), grades=['一年级','二年级','三年级','四年级','五年级','六年级'];
  let mealStage='低年段',mealGrade='全部';
  const inStage=(s,stage)=>stage==='低年段'?grades.slice(0,3).includes(s.grade):grades.slice(3).includes(s.grade);
  function choose(id,items,value,handler){let el=$(id);if(!el)return;el.replaceChildren(...items.map(x=>{let b=document.createElement('button');b.textContent=x;b.className=x===value?'active':'';b.onclick=()=>handler(x);return b}))}
  function renderMealStable(){let root=$('mealcheck');if(!root)return;let intro=root.querySelector('.muted');if(!$('mealStage'))intro.insertAdjacentHTML('afterend','<div class="week-tabs" id="mealStage"></div><div class="time-tabs" id="mealGrade"></div>');let choices=mealStage==='低年段'?grades.slice(0,3):grades.slice(3);choose('mealStage',['低年段','高年段'],mealStage,v=>{mealStage=v;mealGrade='全部';renderMealStable()});choose('mealGrade',['全部',...choices],mealGrade,v=>{mealGrade=v;renderMealStable()});let list=students.filter(s=>!s.special&&inStage(s,mealStage)&&(mealGrade==='全部'||s.grade===mealGrade)),arrived=list.filter(s=>s.care?.every(Boolean)),taken=arrived.filter(s=>s.mealTaken),box=$('mealCheckList');box.innerHTML=list.map(s=>{let ok=s.care?.every(Boolean),done=!!s.mealTaken,p=s.photo_url?`<img class="avatar" src="${s.photo_url}" alt="">`:`<span class="avatar fallback">${s.name.slice(0,1)}</span>`;return `<div class="meal-row ${ok?'':'pending'} ${done?'taken':''}">${p}<div class="name">${s.name}<small style="display:block;color:#6e7b91">${s.grade} · ${s.meal}</small></div><span>${ok?(done?'✓ 已拿饭':'待拿饭'):'尚未到托育'}</span><button class="pill" ${ok?'':'disabled'} onclick="toggleMeal('${s.id}')">${done?'取消拿饭':'点名拿饭'}</button></div>`}).join('')||'<p class="muted">这个筛选条件没有学生。</p>';$('mealRatio').textContent=`${taken.length} / ${arrived.length}`;$('mealProgress').style.width=(arrived.length?taken.length/arrived.length*100:0)+'%';$('mealArrived').textContent=arrived.length;$('mealTaken').textContent=taken.length;$('mealPending').textContent=arrived.length-taken.length}
  window.toggleMeal=async id=>{let s=students.find(x=>String(x.id)===String(id));if(!s||!s.care?.every(Boolean))return;s.mealTaken=!s.mealTaken;save();renderMealStable();if(window.cloud)await cloud.from('attendance').upsert({attendance_date:new Date().toLocaleDateString('sv-SE'),student_id:String(s.id),meal_taken:s.mealTaken})};
  window.toggle=(id,kind,index,value)=>{let s=students.find(x=>String(x.id)===String(id));if(!s)return;s[kind][index]=value;save();renderAttendance();renderAdmin();renderSpecial();renderMealStable()};
  window.editStudent=id=>{let s=students.find(x=>String(x.id)===String(id)),f=$('studentForm');if(!s||!f)return;['id','name','grade','meal','teacher','group','diet','notes','tuition'].forEach(k=>{if(f.elements[k])f.elements[k].value=s[k]||''});if(f.elements.schedule)f.elements.schedule.value=s.schedule||'';$('studentFormTitle').textContent='修改学生资料：'+s.name;$('cancelStudentEdit').classList.remove('hidden');document.querySelector('[data-page="admin"]').click()};
  function orderNav(){let nav=document.querySelector('.nav'),order=['summary','school','care','mealcheck','stay','tuition','admin','special','emergency'];order.forEach((page,i)=>{let b=nav.querySelector(`[data-page="${page}"]`);if(!b)return;b.querySelector('.num').textContent=String(i+1).padStart(2,'0');nav.appendChild(b)})}
  window.addEventListener('load',()=>setTimeout(()=>{orderNav();renderMealStable()},500));
})();

/* 资料显示修复：头像、留校及补习页面使用独立且可保存的数据流程 */
(()=>{
  const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  const weeks=['星期一','星期二','星期三','星期四','星期五'],grades=['一年级','二年级','三年级','四年级','五年级','六年级'];let stayDay=weeks[new Date().getDay()-1]||'星期一',tuDay='星期一',tuStage='全部年段',tuGrade='全部',tuTime='';
  const photo=s=>s?.photo_url?`<img class="avatar" src="${escape(s.photo_url)}" alt="${escape(s.name)}" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'avatar fallback',textContent:'${escape(s.name||'?').slice(0,1)}'}))">`:`<span class="avatar fallback">${escape(s?.name||'?').slice(0,1)}</span>`;
  const localStay=()=>{try{return JSON.parse(localStorage.getItem('fuchengStayMessages')||'[]')}catch{return []}};
  const setStay=data=>localStorage.setItem('fuchengStayMessages',JSON.stringify(data));
  function tabs(id,values,current,click){let el=$(id);if(!el)return;el.replaceChildren(...values.map(v=>{let b=document.createElement('button');b.className=v===current?'active':'';b.textContent=v;b.onclick=()=>{click(v);renderStayFixed()};return b}))}
  function showAvatars(){document.querySelectorAll('#schoolList .student,#careList .student').forEach(el=>{let s=students.find(x=>el.textContent.trim().startsWith(x.name));if(s&&!el.querySelector('.avatar'))el.insertAdjacentHTML('afterbegin',photo(s))})}
  function renderStayFixed(){if(!$('stayWeeks')||!$('stayList'))return;tabs('stayWeeks',weeks,stayDay,v=>stayDay=v);let rows=localStay().filter(x=>x.weekday===stayDay);$('stayList').innerHTML=rows.length?rows.map((r,i)=>{let s=students.find(x=>String(x.id)===String(r.student_id)),mealText=r.meal_mode==='return_meal'?'🍽️ 回来托育吃饭':r.bring_meal?'🍱 需要带饭':'无需带饭';return `<div class="emergency">${photo(s||{name:r.student_name})}<b>${escape(r.student_name)}</b><br>${mealText} · ${escape(r.reason)}<br><button class="outline" onclick="removeStayMessage(${i})">删除</button></div>`}).join(''):'<p class="muted">这一天没有学生留校。</p>'}
  window.removeStayMessage=i=>{let all=localStay(),shown=all.filter(x=>x.weekday===stayDay)[i];setStay(all.filter(x=>x!==shown));renderStayFixed()};
  function bindStayFixed(){let f=$('stayForm');if(!f||f.dataset.fixedStay)return;f.dataset.fixedStay='1';f.onsubmit=async e=>{e.preventDefault();let name=$('stayStudent')?.value.trim(),s=students.find(x=>x.name===name);if(!s)return alert('请从姓名提示中输入完整、正确的学生姓名。');let record={student_id:s.id,student_name:s.name,weekday:f.elements.weekday.value,bring_meal:f.elements.bring_meal.value==='true',reason:f.elements.reason.value};let all=localStay();all.push(record);setStay(all);if(window.cloud)await cloud.from('stay_messages').insert(record);f.reset();renderStayFixed()}}
  function parseTuition(value){return String(value||'').split(/[；;\n]+/).map(raw=>{let m=raw.match(/(星期[一二三四五])[^0-9]*?(\d{1,2}(?::\d{2})?)/);if(!m)return null;let p=raw.split(/[｜|，,]/).map(x=>x.trim()).filter(Boolean);return {week:m[1],time:m[2].includes(':')?m[2]:m[2]+':00',teacher:p[1]||'',subject:p[2]||'',place:p[3]||'',raw}}).filter(Boolean)}
  function renderTuitionFixed(){if(!$('tuitionList'))return;let stageGrades=tuStage==='低年段'?grades.slice(0,3):tuStage==='高年段'?grades.slice(3):grades;let all=students.filter(s=>stageGrades.includes(s.grade)&&(tuGrade==='全部'||s.grade===tuGrade)).flatMap(s=>parseTuition(s.tuition).filter(x=>x.week===tuDay).map(x=>({s,x})));let times=[...new Set(all.map(a=>a.x.time))].sort();if(!times.includes(tuTime))tuTime=times[0]||'';tabs('tuWeek',weeks,tuDay,v=>{tuDay=v;tuTime='';renderTuitionFixed()});tabs('tuTime',times.length?times:['暂无补习时间'],tuTime||'暂无补习时间',v=>{tuTime=v==='暂无补习时间'?'':v;renderTuitionFixed()});tabs('tuStage',['全部年段','低年段','高年段'],tuStage,v=>{tuStage=v;tuGrade='全部';tuTime='';renderTuitionFixed()});tabs('tuGrade',['全部',...stageGrades],tuGrade,v=>{tuGrade=v;tuTime='';renderTuitionFixed()});let show=all.filter(a=>!tuTime||a.x.time===tuTime);$('tuitionList').innerHTML=show.length?show.map(({s,x})=>`<div class="emergency">${photo(s)}<b>${escape(s.name)}</b> · ${escape(s.grade)}<br><b>${escape(x.week)} ${escape(x.time)}</b>${x.teacher?' · '+escape(x.teacher):''}${x.subject?' · '+escape(x.subject):''}${x.place?'<br><span class="muted">地点：'+escape(x.place)+'</span>':''}</div>`).join(''):'<p class="muted">没有符合条件的补习资料。</p>'}
  function bindStudentMedia(){let f=$('studentForm');if(!f||f.dataset.fixedMedia)return;f.dataset.fixedMedia='1';f.addEventListener('submit',()=>{let name=f.elements.name?.value,file=f.elements.photo?.files?.[0],tuition=f.elements.tuition?.value||'';setTimeout(()=>{let s=students.find(x=>x.name===name);if(!s)return;s.tuition=tuition;if(file&&!window.cloud){let reader=new FileReader();reader.onload=()=>{s.photo_url=reader.result;save();showAvatars();renderStayFixed();renderTuitionFixed()};reader.readAsDataURL(file)}else{save();renderTuitionFixed()}},20)},true)}
  const priorAttendance=window.renderAttendance;window.renderAttendance=()=>{priorAttendance();showAvatars()};
  window.addEventListener('load',()=>setTimeout(()=>{bindStayFixed();bindStudentMedia();renderStayFixed();renderTuitionFixed();showAvatars();let nav=document.querySelector('[data-page="stay"]');if(nav){let old=nav.onclick;nav.onclick=e=>{old?.(e);renderStayFixed()}}let tuitionNav=document.querySelector('[data-page="tuition"]');if(tuitionNav)tuitionNav.onclick=e=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));e.currentTarget.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('tuition').classList.remove('hidden');$('pageTitle').textContent='学生补习时间';renderTuitionFixed()}},1000));
})();
